### ISSUE TITLE
Potential inconsistency in step 4

### ISSUE THREAD

**Issue by jennirpf** [raspberrypilearning/c3-wolfram-weather-dashboard#3]
Hi!
As I don't think I came across it in the instructions, I just wanted to check: in step 4, should there be the underscore in the following line of code? 
weatherDashboard[location_] := 
Sorry if I'm asking silly questions!
Thanks,
Jenni

**Comment by PhilipHarney** [comment]
That does, in fact, appear to be correct. It's something to do with Wolfram's pattern evaluation, but I'm honestly not 100% sure why it's being used here… it works though 😄
