### ISSUE TITLE
stray underscore character in the "location_" (Apr 2019)

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/c3-wolfram-weather-dashboard#6]
Feedback from project site

URL: /en/projects/c3-wolfram-weather-dashboard/4 I’m not familiar with Wolfram but it looks like you have a stray underscore character in the "location_" parameter to the weather dashboard function (or it should be described in the discussion if Wolfram needs an underscore for function parameters but not when they are then used).

**Comment by PhilipHarney** [comment]
It's the second thing: it's required. However, it's [a bit complex](https://stackoverflow.com/questions/10689029/why-does-mathematica-use-an-underscore-when-defining-parameters) in terms of the why. I will add a short note that mostly ignores the complexity.

**Comment by libxx1** [comment]
Changing priority to low after confirmation the code is correct but greater clarity would be useful.

**Comment by PhilipHarney** [comment]
Not sure why this was still open, actually. A note explaining that the underscore is needed when creating a parameter is in there, so I must have added it and forgotten to close this. Explaining _why_ it's needed gets more into the fiddly aspects of the Wolfram language than I think we actually want to.
